language: cpp

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
        key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - clang-3.9
      - libc++-dev
      - gcc-5
      - g++-5

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-5
    - compiler: clang
      env: COMPILER=clang++-3.6
    - compiler: clang
      env: COMPILER=clang++-3.7
    - compiler: clang
      env: COMPILER=clang++-3.8
    - compiler: clang
      env: COMPILER=clang++-3.9


install:
    - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER -stdlib=libc++"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi

script: mkdir build && cd build && cmake .. && make && ./tests
